name: Tests & Build

on:
  push:
    branches: [ main, develop, experimental/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    
    - name: Enable corepack
      run: corepack enable
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Run Jest tests
      run: yarn jest --silent --verbose=false --reporters=summary --passWithNoTests
    
    - name: Run type checking
      run: yarn typecheck
    
    - name: Run linting
      run: yarn lint
    
    - name: Build all packages
      run: yarn build:all
    
    - name: Install Playwright browsers
      run: yarn test:e2e:setup
    
    - name: Run Playwright tests
      run: npx playwright test --quiet
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: |
          tests/e2e/html-report/
          tests/e2e/test-results/
          tests/e2e/docs-html-report/
          tests/e2e/docs-test-results/
        retention-days: 30
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: screenshots
        path: tests/e2e/test-results/screenshots/
        retention-days: 30 